version: "2"

services:
  wordpress:
    image: wordpress:4.8.2-php7.1-fpm
    expose:
      - "9000"
    ports:
      - "3306:3306"
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
    mem_limit: ${DOCKER_WORDPRESS_MEM}
    restart: unless-stopped

  nginx:
    image: nginx:1.13
    ports:
      - "8080:80"
    links:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - wordpress
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
    mem_limit: ${DOCKER_NGINX_MEM}
    restart: unless-stopped

  db:
    image: mysql:5.7
    volumes:
      - "./localdb-run.sh:/localdb-run.sh:ro"
      - "./db_data:/var/lib/mysql:rw"
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"
    mem_limit: ${DOCKER_DB_MEM}
    restart: unless-stopped
